server:
  port: 10013
spring:
  application:
    name: nacos-producer
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #集成Swagger高版本启动异常配置，低版本可以不配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: public  # 配置的命名空间，通常是默认的 public
        group: DEFAULT_GROUP  # 配置分组
        file-extension: yaml  # 配置文件扩展名
        username: 'nacos'
        password: 'nacos'
  config:
    import: optional:nacos:nacos-producer-dev.yaml

logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug

# ---------- 以下配置是放在配置中心 ----------
#swagger:
#  enable: true
#  project-leader: tansun
#  leader-email: 123@email
#  application-name: nacos-producer
#  application-version: 1.0
#  application-description: nacos-producer开发环境
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'