server:
  port: 8081

logging:
  level:
    root: info

grpc:
  client:
    GLOBAL:
      enable-keep-alive: true
      address: 'static://127.0.0.1:9000'
      negotiation-type: plaintext

nacos:
  discovery:
    server-addr: 127.0.0.1:8848