server:
  port: 10011
spring:
  application:
    name: nacos-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: public  # 配置的命名空间，通常是默认的 public
        group: DEFAULT_GROUP  # 配置分组
        file-extension: yaml  # 配置文件扩展名
        username: 'nacos'
        password: 'nacos'
  config:
    import: optional:nacos:nacos-config-example.properties

logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug